Include time zone data in Alpine images
sensu/sensu-docker pull request #29
Opened 2021-11-10 18:21 UTC by jamesdphillips

Potential fix for: https://github.com/sensu/sensu-go/issues/4385

---

Signed-off-by: James Phillips <jamesdphillips@gmail.com>

2021-11-10 18:30 UTC, jamesdphillips commented
With the previous image:

<img width="640" alt="Screen Shot 2021-11-10 at 10 29 13 AM" src="https://user-images.githubusercontent.com/194892/141172109-2b137850-9f54-4882-b190-46d537fde9f8.png">

2021-11-19 18:17 UTC, amdprophet approved these changes

2021-11-19 18:18 UTC, amdprophet requested changes
Doesn't appear to be building in CI.

2021-11-19 18:52 UTC, amdprophet approved these changes

2021-11-19 18:52 UTC, merged